### ISSUE TITLE
Software Flow Diagram

### ISSUE THREAD

**Issue by TheAliRobertson** [tamercos/PiCycleSEAT#2]
Great concept and idea for a project! 

Would be good to have a software flow diagram to illustrate the realtime procedures and processes that you will be executing within the Pi! 

- Team 9

**Comment by paoloerc** [comment]
Yes we agree! We will fix this issue for you by 26/03/2018

**Comment by paoloerc** [comment]
Hi there, We have added a flow chart to our github. Another final system diagram and software diagram will be added at a later stage when the final product is close to completion.
