### ISSUE TITLE
Cmake

### ISSUE THREAD

**Issue by 2083008** [tamercos/PiCycleSEAT#3]
Possibly look into Cmake to handle compilation and build

**Comment by tamercos** [comment]
May you elaborate as to why?

A lot is subject to change in our programme. Now that we are currently working on the implementation of the GUI using Qt, Qmake will most likely be our compilation tool.

Please let me know if this is also what you were referring to, in which case I can close the issue!

Thank you.

**Comment by tamercos** [comment]
We are going to close this issue for now as we consider this issue rectified. If you have any additional issues to submit, you are more than welcome to do so!

**Comment by 2083008** [comment]
Sorry, I meant some form of build automation would be nice, Qmake would be perfect!
