### ISSUE TITLE
Software organising

### ISSUE THREAD

**Issue by croaljack0** [tamercos/PiCycleSEAT#4]
A proper directory hierarchy for the software would improve the readability and clarity of how it works.
This could also be discussed in detail the README / documentation.

** Team 10 **

**Comment by paoloerc** [comment]
We will add some order to the files soon. We are still considering merging some files when we create the GUI.

**Comment by paoloerc** [comment]
As it is, gitclone can be used and run as in the readme file instructions. The absolute final order of the code will be established by the project submission date. 
Thanks
