### ISSUE TITLE
Casing Design Diagrams

### ISSUE THREAD

**Issue by danmarwick** [tamercos/PiCycleSEAT#6]
You have the 3D models for the casing.  Could you make those available as pdfs or images that can be viewed without CAD software?  Details on this and the underseat mounting mechanism would be useful.

Daniel - Team 13

**Comment by tamercos** [comment]
Thanks for the idea re including pdf's! Will get on that soon.

Underseat mounting mechanism is still in development, but will add that in a similar fashion once complete

**Comment by tamercos** [comment]
Just uploaded the PDF files now under the 3D print folder!
