### ISSUE TITLE
More visual information and solutions to problems

### ISSUE THREAD

**Issue by acra6488** [tamercos/PiCycleSEAT#8]
Did you encounter any problems and how did you fix them? These could be written down in the Wiki pages under a "Troubleshooting" or "Design advice" section.

Have you started testing? If so some pictures or videos onto your GitHub page or a link to a social media page would be great.
-Aurelie -Team 2

**Comment by paoloerc** [comment]
We'll hopefully be able to make a log of issues and how they were solved. 
Testing has been carried out for the ultrasound transmit/receive and for the vibration motors. We will try to add some photos and videos of this as we begin to prototype. We have still to organise a social media platform for this.

**Comment by paoloerc** [comment]
Hi Aurelie, 
The wiki is now updated with "Issues to look out for". This lists some of the main issues if you were to try and reproduce this project. 
Yes, we have started testing. We will upload some photos of the prototypes to the Github page and link social media when available.
