### ISSUE TITLE
Directory organisation

### ISSUE THREAD

**Issue by CalumWest** [tamercos/PiCycleSEAT#9]
Git could do with restructuring to help clarify code organisation, identify different functionality etc.

**Comment by paoloerc** [comment]
Thanks for the input. We have noticed this is an issue from another comment. We will order the code properly soon. There is still some changes in code especially as we begin to make the GUI.

**Comment by tamercos** [comment]
There is a lot that is subject to change by the 26th unfortunately, so we probably won't have the most organised repository till then! We do intend on restructuring for clarity, but this probably won't happen before the issuing deadline (26th).

So if you don't mind, we will be closing this issue for now with the objective of reorganising the repository for the 16th of April, at which point the project as a whole should be finalised. You are more than welcome to submit further issues upon project completion!

Thank you for your comment!
